export let floor2 =  {
    "parts": [
            {"text": "228", "cols": 2, "rows": 3, "color": "lightblue"},
            {"text": "227", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "226", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "225", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "224", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "223", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "222", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "221", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "220", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "219", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "218", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "217", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "", "cols": 11, "rows": 1, "color": "rgba(250,250,250)"},
            {"text": "", "cols": 9, "rows": 1, "color": "rgba(250,250,250)"},
            {"text": "215", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "216", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "213", "cols": 2, "rows": 3, "color": "lightblue"},
            {"text": "", "cols": 10, "rows": 1, "color": "rgba(250,250,250)"},
            {"text": "201", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "", "cols": 11, "rows": 1, "color": "rgba(250,250,250)"},
            {"text": "212", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "211", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "210", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "209", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "208", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "207", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "206", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "205", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "204", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "203", "cols": 1, "rows": 1, "color": "lightblue"},
            {"text": "202", "cols": 1, "rows": 1, "color": "lightblue"}

    ],
    "columns": 13
}